import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/contexts/LanguageContext";
import Navbar from "./components/Navbar";
import Background from "./components/Background";
import SmoothScrollProvider from "@/contexts/SmoothScrollProvider";

const inter = Inter({
  variable: '--font-inter',
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Now entering Daniel Diaz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="es" className={inter.className}>
      <body className={`${geistSans.variable} ${inter.variable} antialiased text-[#171614]`}>
        <Background />

        <LanguageProvider>
          <SmoothScrollProvider>
          <Navbar />
            {children}
          </SmoothScrollProvider>
        </LanguageProvider>

      </body>
    </html>
  );
}
